name: dio_redirect_interceptor
description: A custom interceptor for Dio HTTP client to handle redirects manually.
version: 1.0.1
homepage: https://github.com/wilinz/dio_redirect_interceptor
documentation: https://github.com/wilinz/dio_redirect_interceptor
repository: https://github.com/wilinz/dio_redirect_interceptor
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ">=3.0.0 <4.0.0"

# Add regular dependencies here.
dependencies:
  dio: ^5.8.0+1
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0

index_generator:
  exclude:
    - 'src/internal/*'
  # Define the paths of the folders in which to generate the index files
  libraries:
    - directory_path: lib
